### PR TITLE
Switch to using JS for all consent settings

### PR DESCRIPTION
**Pull request by ryanmitchell**

### CODE REVIEW

**Comment by anditopping** [comment]
Getting a SyntaxError: Unexpected token ':'. Expected a ';' following a class field. error

**Comment by ryanmitchell** [comment]
Pushed up some fixes

**Comment by ryanmitchell** [comment]
Updated now, you can see it on the exitex dev home page

**Comment by anditopping** [comment]
I always, ALWAYS, forget the bind.

**Pull request merged**
